### ISSUE TITLE
Convert.py is hang forever no output

### ISSUE THREAD

**Issue by ghost** [yistLin/FragmentVC#10]
Thanks you for project, very nice. 

I make run, but not wav is generated and outputs folder empty. 
```
[INFO] Wav2Vec is loaded from wav2vec_small.pt
[INFO] FragmentVC is loaded from fragmentvc.pt
[INFO] Vocoder is loaded from vocoder.pt
[INFO] elasped time 7.709597
[INFO] source waveform shape: torch.Size([1, 86561])
[INFO] target spectrograms shape: torch.Size([1, 80, 97])
[INFO] source Wav2Vec feature shape: torch.Size([1, 270, 768])
[INFO] elasped time 0.137942
[INFO] converted spectrogram shape: torch.Size([270, 80])
[INFO] elasped time 0.710317
```

**Comment by ghost** [comment]
OK, it took 320 seconds. 
The quality not soo good. Can you listen say what wrong? 

[wav.zip](https://github.com/yistLin/FragmentVC/files/5792346/wav.zip)

**Comment by howard1337** [comment]
The quality would be unideal if the provided target utterances are insufficient, since our method extract voice fragments (speaker-dependent latent representation) from the target utterances then further query and fuse them into converted result based on the source utterance.

In your case, the duration of the source utterance is around 6 seconds, while that of the target utterance is below 3 seconds, which is not sufficient.

The example below used the same source utterance (p225_003.wav) as you did and 5 target utterances (artic_a000*.wav) from the CMU Arctic speech databases, which possess better quality.

[example.zip](https://github.com/yistLin/FragmentVC/files/5820158/example.zip)

**Comment by aigerimu** [comment]
Hello. 
My problem is that the output speed is too fast. What`s wrong? 
Here are my source, target and output files. 
[sample.zip](https://github.com/yistLin/FragmentVC/files/9335261/sample.zip)
